project:
  type: website
  output-dir: docs

website:
  title: "Aur√©lien Nicosia"
  site-url: https://AurelienNicosiaUlaval.github.io/web_site/
  repo-url: https://github.com/AurelienNicosiaUlaval/web_site
  repo-actions: [edit, issue]
  navbar:
    logo: assets/logo.svg
    collapse-below: lg
    right:
      - href: index.qmd
        text: Accueil
      - href: enseignement.qmd
        text: Enseignement
      - href: recherche.qmd
        text: Recherche
      - href: innovation.qmd
        text: Innovation P√©dagogique
      - href: ressources.qmd
        text: Autres
#      - href: publications.qmd
#        text: M√©dia
      - href: a-propos.qmd
        text: √Ä propos
      - href: cv/index.qmd
        text: CV
      - text: EN
        href: en/index.qmd
  page-footer:
    left: |
      ¬© 2025 **Aur√©lien Nicosia** ‚Äî Universit√© Laval  
      üìç Qu√©bec, QC ‚Äî ‚úâÔ∏è [aurelien.nicosia@mat.ulaval.ca](mailto:aurelien.nicosia@mat.ulaval.ca)
    right: |
      [GitHub](https://github.com/AurelienNicosiaULaval) ‚Ä¢ 
      [LinkedIn](https://www.linkedin.com/in/aur%C3%A9lien-nicosia-6a52487b/) ‚Ä¢ 
      [ORCID](https://orcid.org/0000-0002-0974-9988)

  search:
    location: navbar
    type: textbox
  favicon: assets/logo.svg
  open-graph:
#    image: assets/og-default.png
    locale: fr_CA

format:
  html:
    theme: cosmo
    css: assets/custom.css
    include-in-header:
      - assets/language-switch.js
    toc: true
    anchor-sections: true
    link-external-newwindow: true
    smooth-scroll: true

lang: fr-CA
execute:
  freeze: auto
